services:
  app:
    build:
      context: ../
      dockerfile: ./docker/golang/Dockerfile
    restart: "no"
    ports:
      - ${HTTPSERVER_PORT}:8080
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DEVELOPMENT_ENVIRONMENT=${DEVELOPMENT_ENVIRONMENT}
    volumes:
      - ../:/service
    depends_on:
      - postgres
    networks:
      - ps
    command: /app/main

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    hostname: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - ps

networks:
  ps:
  internal:

volumes:
  postgres:
    name: ${COMPOSE_PROJECT_NAME}-postgres